CarRepairs/urls.py
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import include
from accounts.views import login_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('Cars/', include('Cars.urls')),
    path('Users/', include('Users.urls')),
    path('Repairs/', include('Repairs.urls')),
    path('login.html', login_view, name='login'),

]

Cars/urls.py
from django.urls import path
from .views import CarListView, CarDetailView

app_name = 'cars'  # Необходимо за именуване на пространството на имена

urlpatterns = [
    path('list/', CarListView.as_view(), name='car_list'),
    path('<int:pk>/', CarDetailView.as_view(), name='car_detail'),
]

Repairs/urls.py
from django.urls import path
from .views import UserListView, UserDetailView

app_name = 'users'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
]

Users/urls.py
from django.urls import path
from .views import UserListView, UserDetailView

app_name = 'users'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
]

Cars/models.py
from django.db import models


class Car(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.PositiveIntegerField()
    vin = models.CharField(max_length=17, unique=True)

    def __str__(self):
        return f"{self.year} {self.make} {self.model}"

Repairs/models.py
from django.db import models


class Repair(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

class User(models.Model):
    # Добавете полета според вашите нужди
    username = models.CharField(max_length=255)
    # Други полета ...

    def __str__(self):
        return self.username

Users/models.py
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

accounts/models.py
from django.db import models

# Create your models here.

commons/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Потребителско име')
    password = forms.CharField(widget=forms.PasswordInput, label='Парола')

Cars/views.py
from django.views.generic import ListView, DetailView
from .models import Car


class CarListView(ListView):
    model = Car
    template_name = 'car_list.html'


class CarDetailView(DetailView):
    model = Car
    template_name = 'car_detail.html'

Repairs/views.py
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import User  # Проверете дали моделът е правилно указан


class UserListView(ListView):
    model = User
    template_name = 'user_list.html'

class UserDetailView(DetailView):
    model = User
    template_name = 'repairs/user_detail.html'

Users/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import User


class UserListView(ListView):
    model = User
    template_name = 'user_list.html'

class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.shortcuts import render


# Предполага се, че имате собствена форма за логин

def login_view(request):
    if request.method == 'POST':
        # Обработка на формата за вход
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # Влизане успешно, пренасочване към началната страница или друга страница
            return redirect('index.html')  # Променете 'home' с името на вашата начална страница
        else:
            # Невалиден вход, може да покажете грешка или пренасочите към същата страница за вход
            return render(request, 'login.html', {'error': 'Invalid username or password'})

    else:
        # Показване на страницата за вход (можете да имате собствен шаблон за вход)
        return render(request, 'login.html')

Cars/templates/car_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ car }}</title>
</head>
<body>
    <h1>{{ car }}</h1>
    <p>Make: {{ car.make }}</p>
    <p>Model: {{ car.model }}</p>
    <p>Year: {{ car.year }}</p>
    <p>VIN: {{ car.vin }}</p>
    <!-- Други полета от модела, които искате да включите -->

    <!-- Пример за връзка към списъка с коли -->
    <p><a href="{% url 'car_list' %}">Back to Car List</a></p>
</body>
</html>

Cars/templates/car_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car List</title>
</head>
<body>
    <h1>Car List</h1>
    <ul>
        {% for car in object_list %}
            <li>
                <a href="{% url 'car_detail' car.pk %}">{{ car }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

Users/templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User List</title>
</head>
<body>
    <h1>User List</h1>

    {% if user_list %}
        <ul>
            {% for user in user_list %}
                <li>
                    <a href="{% url 'users:user_detail' user.pk %}">{{ user.username }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No users available.</p>
    {% endif %}
</body>
</html>

accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
   <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html><html lang='en' class=''>
<head><script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/frytyler/pen/EGdtg" />

<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'><script src='https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js'></script>
<style class="cp-pen-styles">@import url(https://fonts.googleapis.com/css?family=Open+Sans);
.btn { display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 18px; color: #333333; text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#ffffff, endColorstr=#e6e6e6, GradientType=0); border-color: #e6e6e6 #e6e6e6 #e6e6e6; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); border: 1px solid #e6e6e6; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); cursor: pointer; *margin-left: .3em; }
.btn:hover, .btn:active, .btn.active, .btn.disabled, .btn[disabled] { background-color: #e6e6e6; }
.btn-large { padding: 9px 14px; font-size: 15px; line-height: normal; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; }
.btn:hover { color: #333333; text-decoration: none; background-color: #e6e6e6; background-position: 0 -15px; -webkit-transition: background-position 0.1s linear; -moz-transition: background-position 0.1s linear; -ms-transition: background-position 0.1s linear; -o-transition: background-position 0.1s linear; transition: background-position 0.1s linear; }
.btn-primary, .btn-primary:hover { text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25); color: #ffffff; }
.btn-primary.active { color: rgba(255, 255, 255, 0.75); }
.btn-primary { background-color: #4a77d4; background-image: -moz-linear-gradient(top, #6eb6de, #4a77d4); background-image: -ms-linear-gradient(top, #6eb6de, #4a77d4); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#6eb6de), to(#4a77d4)); background-image: -webkit-linear-gradient(top, #6eb6de, #4a77d4); background-image: -o-linear-gradient(top, #6eb6de, #4a77d4); background-image: linear-gradient(top, #6eb6de, #4a77d4); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#6eb6de, endColorstr=#4a77d4, GradientType=0);  border: 1px solid #3762bc; text-shadow: 1px 1px 1px rgba(0,0,0,0.4); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.5); }
.btn-primary:hover, .btn-primary:active, .btn-primary.active, .btn-primary.disabled, .btn-primary[disabled] { filter: none; background-color: #4a77d4; }
.btn-block { width: 100%; display:block; }

* { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; -ms-box-sizing:border-box; -o-box-sizing:border-box; box-sizing:border-box; }

html { width: 100%; height:100%; overflow:hidden; }

body {
	width: 100%;
	height:100%;
	font-family: 'Open Sans', sans-serif;
	background: #092756;
	background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
}
.login {
	position: absolute;
	top: 50%;
	left: 50%;
	margin: -150px 0 0 -150px;
	width:300px;
	height:300px;
}
.login h1 { color: #fff; text-shadow: 0 0 10px rgba(0,0,0,0.3); letter-spacing:1px; text-align:center; }

input {
	width: 100%;
	margin-bottom: 10px;
	background: rgba(0,0,0,0.3);
	border: none;
	outline: none;
	padding: 10px;
	font-size: 13px;
	color: #fff;
	text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
	border: 1px solid rgba(0,0,0,0.3);
	border-radius: 4px;
	box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
	-webkit-transition: box-shadow .5s ease;
	-moz-transition: box-shadow .5s ease;
	-o-transition: box-shadow .5s ease;
	-ms-transition: box-shadow .5s ease;
	transition: box-shadow .5s ease;
}
input:focus { box-shadow: inset 0 -5px 45px rgba(100,100,100,0.4), 0 1px 1px rgba(255,255,255,0.2); }
</style></head><body>
<div class="login">
	<h1>Login</h1>
    <form method="post">
    	<input type="text" name="u" placeholder="Username" required="required" />
        <input type="password" name="p" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
</div>
<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script >/*

I built this login form to block the front end of most of my freelance wordpress projects during the development stage.

This is just the HTML / CSS of it but it uses wordpress's login system.

Nice and Simple

*/
//# sourceURL=pen.js
</script>
</body></html>
{% endblock %}

commons/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login Page</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Пътят към вашия CSS файл -->
    <title>CarBook</title>
    <title>{% block title %}My Website{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Car Repairs</a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Register</a>
        </li>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
{% block content %}{% endblock %}

  <!--  <script src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
-->
</body>
</html>

commons/templates/index.html
{% load static %}


<!DOCTYPE html>

<html lang="en">
<head>

	<title>Login Page</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Пътят към вашия CSS файл -->
    <title>CarBook</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Car Repairs</a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
             <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="#">Register</a>
        </li>

        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

  <!--  <script src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/cars/car_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ car }}</title>
</head>
<body>
    <h1>{{ car }}</h1>
    <p>Make: {{ car.make }}</p>
    <p>Model: {{ car.model }}</p>
    <p>Year: {{ car.year }}</p>
    <p>VIN: {{ car.vin }}</p>
    <!-- Други полета от модела, които искате да включите -->
</body>
</html>

templates/cars/car_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car List</title>
</head>
<body>
    <h1>Car List</h1>
    <ul>
        {% for car in object_list %}
            <li>
                <a href="{% url 'car_detail' car.pk %}">{{ car }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Service</title>

</head>
<body touchstart="">
    <img src="{% static 'images/background.png' %}"  class='auth_background' alt="auth background">
    <header class="header">


        <div class="header__logo">
            <a href="{% url 'home page' %}"><img src="{% static 'images/logo.png' %}" alt="Logo img"></a>
        </div>
        {% block menu %}
            <nav class="middle-menu">

                <ul class ="menu">
                    <li class="middle-menu__list">
                        <a href="{% url 'home page' %}" ><i class="fas fa-home"></i></a>
                    </li>
                    {% if user.is_authenticated %}
                        <script type="text/javascript" src="{% static 'js/menu.js' %}"></script>
                        {% if user.is_customer %}
                            <li class="middle-menu__list">
                                <a href="{% url 'garage' %}" ><i class="fas fa-warehouse"></i></a>
                            </li>
                        {% elif user.is_staff or user.is_superuser %}
                        <li class="middle-menu__list">
                            <a href="{% url 'admin:index' %}" ><i class="fas fa-users-cog"></i></a>
                        </li>
                        {% endif %}
                    {% endif %}
                    <li class="middle-menu__list">
                        <a href="{% url 'gallery page' %}" ><i class="fas fa-images"></i></a>
                    </li>
                    <li class="middle-menu__list">
                        <a href="{% url 'contacts' %}" ><i class="fas fa-address-card"></i></a>
                    </li>
                </ul>
            </nav>
        {% endblock %}
        <section class="auth_system">

            <ul class="auth_system__menu">
                {% if not user.is_authenticated %}
                        <div class="auth_content">
                            <a href="{% url 'singin page' %}" class="btn">Sing in</a>
                            <a href="{% url 'singup page' %}" class="btn">Sing up</a>
                        </div>

                {% else %}
                    <li >
                        {% if user.is_customer %}
                            <a href="{% url 'profile' %}" class="btn auth_system__links">
                                Profile
                            </a>
                        {% elif not user.is_superuser %}
                            <a href="{% url 'employee profile' user.pk %}" class="btn auth_system__links">
                                Profile
                            </a>
                        {% endif %}
                    </li>
                    <li>
                        <a href="{% url 'logout' %}" class="btn auth_system__links">
                            Logout
                        </a>
                    </li>
                {% endif %}
            </ul>
        </section>
    </header>
    <main class='main__content'>
        <section class="hero">
            {% block cover_car %}
                <img src="{% static 'images/hero.png' %}" alt="">
            {% endblock  %}
            {% block content %}
            {% endblock %}
        </section>
    </main>


    {% block brands %}
        <section class="brands">
            <div class="items">
                {% if cars %}
                    {% for car in cars %}
                        <img src="{% static 'images/car_brands/' %}{{ car.image }}" alt="{{ car.brand }}" class="brands__logo">
                    {% endfor %}
                {% endif %}
            </div>

        </section>
    {% endblock %}

    {% block footer %}
        <footer class="footer">
            <span>Created by Chavdar Stoiliv <a class="github_url" href='https://github.com/ChavdarStoilov'><i class="fab fa-github"></i></a></span>
        </footer>
    {% endblock  %}

{% block script %}
{% endblock  %}
</body>
</html>